const { Character } = require('../models')

const characterData = [
    {
        name: 'Shrek',
        damage: 100,
        health: 100,
        background: 'Lives in a Swamp, friends with donkey, has many layers like an onion.',
        race: 'Ogre',
        class_id: 1,
        user_id: 1,
    },
    {
        name: "Tyr",
        damage: 100,
        health: 100,
        background: 'Lost his hand to a wolf.',
        race: 'Human',
        class_id: 2,
        user_id: 1,
    },
    {
        name: 'Robin Hood',
        damage: 75,
        health: 100,
        background: 'Steals from the rich to give to the poor.',
        race: 'Elf',
        class_id: 3,
        user_id: 1,
    },
    {
        name: 'Bunnicula',
        damage: 100,
        health: 35,
        background: 'Is a vampire bunny, also vegan.',
        race: 'Undead',
        class_id: 4,
        user_id: 1,
    },
    {
        name: 'Tigger',
        damage: 60,
        health: 100,
        background: 'Known for his TTFN, and his enjoyment of bouncing.',
        race: 'Elf',
        class_id: 2,
        user_id: 2,
    },
    {
        name: 'Casper',
        damage: 1,
        health: 1,
        background: 'Very friendly neighborhood orc.',
        race: 'Undead',
        class_id: 2,
        user_id: 2,
    },
    {
        name: 'Popeye',
        damage: 100,
        health: 100,
        background: 'Sailor, loves himself some spinich.',
        race: 'Human',
        class_id: 2,
        user_id: 2,
    },
    {
        name: 'Brutus',
        damage: 100,
        health: 100,
        background: 'Sailor, does not like Popeye.',
        race: 'Human',
        class_id: 5,
        user_id: 2,
    },
    {
        name: 'Invader Zim',
        damage: 1,
        health: 100,
        background: 'Alien invader set on world domination.',
        race: 'Undead',
        class_id: 6,
        user_id: 3,
    },
    {
        name: 'Bo Zo',
        damage: 100,
        health: 100,
        background: 'Circus clown, known for having very large shoes, bright clothes, and a nose that honks when squeezed.',
        race: 'Human',
        class_id: 2,
        user_id: 3,
    },
    {
        name: 'Dilinger',
        damage: 40,
        health: 100,
        background: 'Bank robber.',
        race: 'Dwarf',
        class_id: 5,
        user_id: 3,
    },
    {
        name: 'Gir',
        damage: 1,
        health: 100,
        background: 'Alien invader assistant, likes food, easily distracted.',
        race: 'Elf',
        class_id: 6,
        user_id: 3,
    },
];

const seedCharacters = () => Character.bulkCreate(characterData);

module.exports = seedCharacters;